# Generated by Django 5.1 on 2024-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('AGE', models.IntegerField()),
                ('PHONE', models.IntegerField()),
                ('ADDRESS', models.CharField(max_length=50)),
                ('TOKENNUMBER', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('GENDER', models.CharField(max_length=40)),
                ('PHONE', models.IntegerField()),
                ('AGE', models.IntegerField()),
                ('CATAGORY', models.CharField(max_length=40)),
                ('EMAIL', models.EmailField(max_length=30)),
                ('ADDRESS', models.TextField()),
                ('DUTY_time', models.TimeField()),
                ('USERNAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=70)),
                ('AGE', models.IntegerField()),
                ('ADDRESS', models.CharField(max_length=40)),
                ('PHONE', models.IntegerField()),
                ('DOB', models.TimeField()),
                ('GENDER', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=100)),
                ('Username', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=20)),
                ('Section', models.CharField(max_length=40)),
                ('Phone', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('ADDRESS', models.TextField()),
                ('PHONE', models.IntegerField()),
                ('GENDER', models.CharField(max_length=40)),
                ('AGE', models.IntegerField()),
                ('DOB', models.TimeField()),
                ('QUALIFITION', models.CharField(max_length=30)),
                ('EMAIL', models.EmailField(max_length=40)),
                ('USERNAME', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
