# Generated by Django 5.1 on 2024-09-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='GENDER',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='TOKENNUMBER',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
    ]
