# Generated by Django 5.1 on 2024-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0002_booking_gender_alter_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='DOB',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='DOB',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
