# Generated by Django 5.1 on 2024-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0003_alter_doctors_dob_alter_patients_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='ADDRESS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='AGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='CATAGORY',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='DUTY_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='GENDER',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
