# Generated by Django 5.1 on 2024-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_alter_doctors_address_alter_doctors_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
